### ISSUE TITLE
Backup not working

### ISSUE THREAD

**Issue by pelcasandra** [yorokobicom/agent#3]
When I try to perform a backup running `yorokobi-backup` I get the following error. 

```
martin@martin-VirtualBox:~/Repos/yorokobi-agent$ yorokobi-backup
The agent doesn't appear running; ensure the agent is started.
```

And the daemon returns the following error. 

```
backup 112BxTr_vEPBgNNWYbnb is starting
backup with port 50712 and token 112BxTr_vEPBgNNWYbnb
backup-now: accepted
None
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/yorokobi-0.1.0-py3.6.egg/yorokobi/backup.py", line 63, in run
    self.dump_databases(temporary_dir)
  File "/usr/local/lib/python3.6/dist-packages/yorokobi-0.1.0-py3.6.egg/yorokobi/backup.py", line 98, in dump_databases
    for database in selected_dbs:
TypeError: 'NoneType' object is not iterable

about to terminate the backup
200
{'id': 'FMFSndIMJjhvQlXAwDhm', 'hostname': 'backup.yorokobi.com', 'port': 50228, 'token': 'FMFSndIMJjhvQlXAwDhm', 'state': 'initial'}
{"id":"FMFSndIMJjhvQlXAwDhm","hostname":"backup.yorokobi.com","port":50228,"token":"FMFSndIMJjhvQlXAwDhm","state":"initial"}

```

**Comment by Sonkun** [comment]
Made some progress but I'm running out of time, will finish that tonight. The `pg_dumpall` seems to be asking password for every databases (which is supposed to be the same), could be a challenge to get that one working. I'll see.

**Comment by pelcasandra** [comment]
You should not use `pg_dumpall` because it is slower and it doesn't allow to take advantage of _custom_ format which is the one we'll use. Use `pg_dump` instead and iterate all tables internally. 

Check this guide I wrote on the subject: https://www.yorokobi.com/guides/backup-and-restore-a-postgresql-database

**Comment by pelcasandra** [comment]
The query should look like this.

`pg_dump -Fc database_name > database_name.dump`.

We can match the file name with the database name.

**Comment by Sonkun** [comment]
Okay, good news, backing up individual databases one by one works now (sending the patch in a minute).

However fews things:
1) Sending the tarball with remofile fails (probably a port problem or server instance not configured correctly, or wrong token is sent)
2) Backups in yorokobi dashboard still shows as "In the middle of a backup", if the "terminate backup" signal is never sent. It would probably be a good idea to mark it as failure after a given time. 
3) Old agents still shows in dashboard after being unregistered
4) In the dashboard there's no way to understand which ID is associated to the agent

**Comment by pelcasandra** [comment]
1. May I ask you to share the log of the moment it is failing to take a look? By the way, I noticed the IP address [is still hardcoded](https://github.com/yorokobicom/agent/blob/master/yorokobi/backup.py#L160). Im not sure this is a good idea as people start installing the agent and the IP could eventually change. Can you replace it with `backup.yorokobi.com` instead? 

2. This is true. However, as amount of time given is arbitrary it could happen that the backup didn't failed but simply it was a really big file sent from a really slow connection. Is there any way that I can check the status of a remofile? With such an option I could set up a process to perform a check regularly and if there is nothing being transmitted simply mark it as cancelled. That would be more reliable.

3. They are differentiated now with a lower opacity. I'll make this even more clear on the UI. At least for now, de-registering an agent is not the same as deleting the agent. Backups are still there when needed (as long as the retention period is valid). What probably should be added is an option in the dashboard to remove completely the agent and/or its backups.

**Comment by Sonkun** [comment]
1. Right, the IP is hard-coded for now. I replaced it with backup.yorokobi.com, hope it works (it's using other network library under the hood so not sure how it plays with it). Could you check the latest commit, build the snap package (or use `yorokobid` directly), and try to do a backup. On my computer it's blocked Remofile upload of the tarball. The log shows the tarball filename, Remofile port and token. 

2. Yeah, right. Not sure what the best solution is. I don't think an option in Remofile to see if there's anybody uploading a file would help (plus it would introduce other problems as Remofile handles connection loss transparently). I think defining a maximum backup duration makes more sense here, if it fails due to temporary slow connection, then it could just fail and try later. Since only the Yorokobi agent has the credentials to upload anything, the best would give him a limit amount of time to upload the backup tarball, and send a "terminate backup" signal. What's your thoughts ? 

3. OK
4. Ahh, I didn't notice, sorry :)

**Comment by Sonkun** [comment]
Any progress on that one, or you couldn't get the agent working because of the other issues ?

**Comment by pelcasandra** [comment]
> Any progress on that one, or you couldn't get the agent working because of the other issues ?

I couldn't get to this part as the agent is giving errors before I can't configure it. Please check the other issues reported.

**Comment by Sonkun** [comment]
Not sure what issue prevents from testing that part.

If it's about snap, how about running the agent manually ? 

```
python3 -m virtualenv python-env
source python-env/bin/activate

git clone https://github.com/yorokbicom/agent
cd agent
python setup.py install

mkdir -p ~/Desktop/test-agent/agent1
cd ~/Desktop/test-agent/agent1
yorokobid&
yorokobi setup
yorokob backup
```

Let me know if you need any assistance (also reachable on Skype).

**Comment by pelcasandra** [comment]
Thanks for these clarifications. I can confirm I can test now both on Docker and regular Ubuntu using python. 

I have found 3 issues, two of them preventing the backup to complete. 

One is already fixed and the other is left to you to review: 

- [x] **Just fixed** - The API didn't recognize the name of the file uploaded. Now it does. 
- [ ] [Backup is sending a new backup request instead of mark it as complete](#17).

I also noticed that remofile is started in the backup server asynchronously a few seconds after the API returns the token and the port. This can cause the agent to try to upload a backup before remofile started. I will think a bit more about this but probably I will add a state to the backup to state when it is 'ready' to receive the backup. Will post an issue about this shortly.

**Comment by Sonkun** [comment]
I fixed the malformed HTTP request. 

Why should it have to recognize the name of a file ? You could consider everything uploaded in the root directory of the Remofile instance as the backup files.

Don't worry about delayed startup. Remofile is handling it. A timeout duration should be set on the agent side, I think by default it's 10 seconds.

**Comment by Sonkun** [comment]
Oh, I forgot to say that on my side, it's still blocking at the upload tarball step (it can't communicate with the Remofile server, maybe port blocked, or token/port incorrect).

**Comment by pelcasandra** [comment]
> Backups in yorokobi dashboard still shows as "In the middle of a backup", if the "terminate backup" signal is never sent. It would probably be a good idea to mark it as failure after a given time.

I just implemented a new feature in the API that mark all `initial` or `waiting` backups with more than 24 hours of being created as `canceled`.

**Comment by Sonkun** [comment]
Nothing changed on my side, still can't upload the tarball, and by consequences I can't reach the code you are reaching. 

```
2019-02-04 04:33:24,697 - yorokobi - INFO - Agent has successfull started
2019-02-04 04:33:28,272 - yorokobi - INFO - The agent received a {'type': <Request.BACKUP_NOW: 5>} request
2019-02-04 04:33:28,272 - yorokobi - INFO - A manual backup is requested
2019-02-04 04:33:28,272 - yorokobi - INFO - Sending a backup request to Yorokobi server
2019-02-04 04:33:28,274 - yorokobi - INFO - Request data is {'agent_id': 'uLPtJZvx4UD0R_lfKf', 'hostname': 'vulpix', 'ip_address': '127.0.1.1'}
2019-02-04 04:33:29,439 - yorokobi - INFO - Response status is 200
2019-02-04 04:33:29,440 - yorokobi - INFO - Response data is:
2019-02-04 04:33:29,440 - yorokobi - INFO - {'id': 'N6qsAYaqiM5TLFXtRANa', 'hostname': 'backup.yorokobi.com', 'port': 32839, 'token': 'N6qsAYaqiM5TLFXtRANa', 'state': 'initial'}
2019-02-04 04:33:29,440 - yorokobi - INFO - Got a positive response from server; backup was accepted
2019-02-04 04:33:29,440 - yorokobi - INFO - Reading response to retrieve the backup ID, the remofile port and the remofile token
2019-02-04 04:33:29,440 - yorokobi - INFO - Backup ID is N6qsAYaqiM5TLFXtRANa
2019-02-04 04:33:29,440 - yorokobi - INFO - Remofile port is 32839
2019-02-04 04:33:29,441 - yorokobi - INFO - Remofile token is N6qsAYaqiM5TLFXtRANa
2019-02-04 04:33:29,441 - yorokobi - INFO - Starting a backup in external thread
2019-02-04 04:33:29,441 - yorokobi - INFO - Starting backup now
2019-02-04 04:33:29,441 - yorokobi - INFO - The backup request was accepted
2019-02-04 04:33:29,441 - yorokobi - INFO - Remofile port: 32839
2019-02-04 04:33:29,441 - yorokobi - INFO - Remofile token: N6qsAYaqiM5TLFXtRANa
2019-02-04 04:33:29,443 - yorokobi - INFO - ['postgres']
2019-02-04 04:33:42,350 - yorokobi - INFO - Sending the tarball
2019-02-04 04:33:42,350 - yorokobi - INFO - Sending '/tmp/tmpi2j96_30/2019.02.04.04.02.42.tar.gz' to backup.yorokobi.com using Remofile protocol with port 32839 and token 'N6qsAYaqiM5TLFXtRANa'...
```

**Comment by pelcasandra** [comment]
You can try now.
